--
-- PostgreSQL database dump
--

\restrict PFbrgEf0OnIbT0M5zFiy0lGN9EgBgRW7fG0dLnV9hKv02MbdrCrTGxBUChCb7Wm

-- Dumped from database version 16.14
-- Dumped by pg_dump version 16.14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: doctrine_migration_versions; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.doctrine_migration_versions (
    version character varying(191) NOT NULL,
    executed_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    execution_time integer
);


ALTER TABLE public.doctrine_migration_versions OWNER TO app;

--
-- Name: message; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.message (
    id integer NOT NULL,
    author character varying(255) NOT NULL,
    content text NOT NULL,
    created_at timestamp(0) without time zone NOT NULL
);


ALTER TABLE public.message OWNER TO app;

--
-- Name: message_id_seq; Type: SEQUENCE; Schema: public; Owner: app
--

ALTER TABLE public.message ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.message_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: doctrine_migration_versions; Type: TABLE DATA; Schema: public; Owner: app
--

COPY public.doctrine_migration_versions (version, executed_at, execution_time) FROM stdin;
DoctrineMigrations\\Version20260827112714	2026-08-27 11:28:25	67
\.


--
-- Data for Name: message; Type: TABLE DATA; Schema: public; Owner: app
--

COPY public.message (id, author, content, created_at) FROM stdin;
1	Adam	Html	2026-08-28 13:40:56
2	Ania	Css	2026-08-28 13:41:00
3	Marcin	Js	2026-08-28 13:41:07
4	Adam	PHP	2026-08-28 13:41:14
5	Ania	C#	2026-08-28 13:41:21
6	Marcin	C++	2026-08-28 13:41:25
\.


--
-- Name: message_id_seq; Type: SEQUENCE SET; Schema: public; Owner: app
--

SELECT pg_catalog.setval('public.message_id_seq', 6, true);


--
-- Name: doctrine_migration_versions doctrine_migration_versions_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.doctrine_migration_versions
    ADD CONSTRAINT doctrine_migration_versions_pkey PRIMARY KEY (version);


--
-- Name: message message_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.message
    ADD CONSTRAINT message_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict PFbrgEf0OnIbT0M5zFiy0lGN9EgBgRW7fG0dLnV9hKv02MbdrCrTGxBUChCb7Wm

